### ISSUE TITLE
handleDateClick点击后没有添加日程

### ISSUE THREAD

**Issue by yzf1116** [Inspiration1/asteroid#3]
handleDateClick (arg) {
      if (confirm('Would you like to add an event to ' + arg.dateStr + ' ?')) {
        this.calendarEvents.push({ // add new event data
          title: 'New Event',
          start: arg.date,
          allDay: arg.allDay
        })
      }
    },
点击确定后怎么没有添加日程，

**Comment by inspiration1** [comment]
Fixed
