### ISSUE TITLE
想问下如何调整axis Y轴的顺序?

### ISSUE THREAD

**Issue by curryhh** [Inspiration1/asteroid#7]

**Comment by inspiration1** [comment]
具体描述下？

**Comment by curryhh** [comment]
比如我现在图表的创建顺序是
chart.interval() .position('time*clean') .color('#35B8E0');
chart.line() .position('time*use') .color('#6D757D');  
这样的话axis的顺序是先clean（最左边）use（在右边），我可以调整axis顺序吗？

**Comment by inspiration1** [comment]
参考下其中的position属性：https://antv.vision/old-site/g2/doc/tutorial/start/attr.html

**Comment by curryhh** [comment]
没看懂，大佬可以指点一下吗？
