### ISSUE TITLE
请问,这些not found怎么解决呢?

### ISSUE THREAD

**Issue by wmo123** [Inspiration1/asteroid#8]
![image](https://user-images.githubusercontent.com/47963460/82807509-78710580-9eba-11ea-9502-5169ed0448d9.png)

**Comment by inspiration1** [comment]
https://github.com/tinymce/tinymce/issues/5687
看起来tinymce在最近的修改中把icon拆分出去了，需要单独引用。
`import 'tinymce/icons/default`

**Comment by wmo123** [comment]
谢谢回复，确实需要单独引用icon。
